# Generated by Django 5.2 on 2025-04-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('session_key', models.CharField(max_length=100)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ipcamera')),
            ],
        ),
    ]
