# Generated by Django 5.2 on 2025-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('channels', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
