# Generated by Django 5.2.1 on 2025-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user_session_key', 'product')},
        ),
    ]
