# Generated by Django 5.2.1 on 2025-05-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
