# Generated by Django 5.2 on 2025-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_harddisk_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='nvr',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
