# Generated by Django 5.2 on 2025-04-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcamera',
            name='available_mps',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
